on:
  release:
    types:
      - published

name: release-3rdparty
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          check-latest: true
      - name: build-gradle
        run: ./gradlew clean build -x test --build-cache --scan -s
      - name: docker
        continue-on-error: true
        env:
          MULEFD_USER: ${{ secrets.MULEFD_USER }}
          MULEFD_TOKEN: ${{ secrets.MULEFD_TOKEN }}
        run: ./misc/updatecontainer.sh
      - name: homebrew
        continue-on-error: true
        env:
          MULEFD_USER: ${{ secrets.MULEFD_USER }}
          MULEFD_TOKEN: ${{ secrets.MULEFD_TOKEN }}
        run: ./misc/updatebrew.sh
      - name: scoop
        continue-on-error: true
        env:
          MULEFD_USER: ${{ secrets.MULEFD_USER }}
          MULEFD_TOKEN: ${{ secrets.MULEFD_TOKEN }}
        run: ./misc/updatescoop.sh
      - name: sdkman
        continue-on-error: true
        env:
          SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
          SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
        run: ./misc/updatesdkman.sh
